### ISSUE TITLE
It seems can't work with neocomplete?

### ISSUE THREAD

**Issue by morefreeze** [reedes/vim-lexical#10]
I install neocomplete plugin too, and I find after `call lexical#init()` vim will freeze about 3~5 seconds when I type something and it will pop up completion menu. If I use `:NeoCompleteDisable` vim will go well.
But I find I can't disable it with this `autocmd FileType text,markdown,mkd,textile NeoCompleteDisable`. How can I do?

**Comment by reedes** [comment]
If the associated files are present, _Lexical_ configures vim to use a thesaurus (~/.vim/thesaurus/mthesaur.txt) and dictionary (/usr/share/dict/words). Without neocomplete this happens in a fraction of a second.

It may be that neocomplete is processing those files to load them into memory for quick runtime access. You can confirm this by overriding the defaults or temporarily renaming the files.

When I have a chance, I'll try neocomplete to see if I can reproduce the problem.

**Comment by morefreeze** [comment]
Thanks for your quick answer. You're right. neocomplete will load these files. I confirm this by renaming the `words` file.

I figure out a solution to this, in other words, I found how to disable neocomplete in text file type correctly. It seems a trade-off solution I can find. Thanks again.

```
" let g:neocomplete#enable_at_startup = 1
augroup neocomplete
    autocmd!
    autocmd FileType * NeoCompleteEnable
augroup END
augroup lexical
    autocmd FileType text,markdown,mkd,textile NeoCompleteDisable
augroup END
```
