### ISSUE TITLE
Detecting links?

### ISSUE THREAD

**Issue by macintacos** [reedes/vim-lexical#18]
Ideally it'd be great if the plugin could not have issues with links, is there a way to make sure that it understands what links are and just assume that they are spelled correctly?

**Comment by alerque** [comment]
Which regions of a buffer are eligible for spell checking and which are not is determined by the relevant syntax plugin. The same rules that give different bits of a file different assignments in a color scheme based on how they parse the syntax also marks those bits as being part of the spelling system or not.

In other words this plugin is not responsible for detecting what bits of a file to spellcheck or not. You should open this issue under whatever syntax plugin you are using. For example for Markdown there is the built in syntax, [tpope's plugin](https://github.com/tpope/vim-markdown), [plasticboy's plugin](https://github.com/plasticboy/vim-markdown), [fmoralesc's plugin](https://github.com/vim-pandoc/vim-pandoc-syntax), and many others. Each of these is going to have slightly different syntax rules and perhaps highlight different bits for spell correction (or not).

**Comment by macintacos** [comment]
Got it, makes sense, thanks @alerque. I'll close this out.
