### ISSUE TITLE
Insert mode spelling suggest key conflicts with terminals

### ISSUE THREAD

**Issue by alerque** [reedes/vim-lexical#3]
The documentation notes the following:

> For spelling suggestions while in Insert mode:
> - `«CTRL-X»` `«CTRL-S»` - suggest spelling

This may work from GUI client versions of VIM, but it doesn't work from the terminal where CTRL+S is usually intercepted by the terminal emulator and interpreted as a STOP character.

Is there a way to re-map this and can the documentation be updated to reflect how this is done?

**Comment by reedes** [comment]
I can see that being a problem. It looks like you can use `Ctrl-X s` in a terminal, according to

```
:help compl-spelling
```

A pull request is welcome to improve the README. Otherwise I'll get to it later.

**Comment by reedes** [comment]
Should be fixed now.

**Comment by alerque** [comment]
Hey hey that's great, and thanks. I guess I can close this tab now. I _was_ going to try to fix this up myself eventually.
